CREATE TABLE IF NOT EXISTS sales (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    region VARCHAR(100) NOT NULL,
    product VARCHAR(200) NOT NULL,
    revenue NUMERIC(12,2) NOT NULL,
    units INTEGER NOT NULL DEFAULT 1,
    customer_id INTEGER
);

CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    cost NUMERIC(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS customers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    region VARCHAR(100) NOT NULL,
    segment VARCHAR(50) NOT NULL DEFAULT 'Roznica',
    created_at DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS employees (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    department VARCHAR(100) NOT NULL,
    salary NUMERIC(12,2) NOT NULL,
    hire_date DATE NOT NULL DEFAULT CURRENT_DATE
);
